name: Scheduled Master Runner

on:
  workflow_dispatch:      # manual trigger
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes

concurrency:
  group: master-script
  cancel-in-progress: true

jobs:
  run-master:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # allow the GITHUB_TOKEN to push back
          persist-credentials: true
          # fetch full history to allow git diff
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      - name: Run master.py
        run: python master.py

      - name: Commit & push updated Sheets
        shell: bash
        run: |
          # configure git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # stage changes
          git add Sheets/

          # only commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes in Sheets/, skipping commit."
          else
            git commit -m "chore: update Sheets via scheduled runner"
            git push
          fi
