name: Scheduled Master Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

concurrency:
  group: master-script
  cancel-in-progress: true

jobs:
  run-master:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run master.py
        run: |
          cd ${{ github.workspace }}
          python master.py

      - name: Upload generated Sheets
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: leve-profits-sheets
          path: Sheets/
